name: bridgme
version: 1.0.0+1
publish_to: none
description: Patient application for bridge me theraputic app
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  effective_dart: 1.3.1
  get:
    path: ../
  shared_preferences: ^2.0.13
  wave: ^0.2.0
  fluttertoast: ^8.0.3
  flutter_easyloading: ^3.0.0
  flutter_svg: ^1.0.3
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.0.0
  cloud_firestore:
  firebase_auth:
  eva_icons_flutter: ^3.0.2
  permission_handler: ^9.2.0
  instant: ^0.4.1
  hexcolor: ^2.0.5
  google_sign_in:
  readmore: ^2.1.0
  flutter_facebook_auth: ^4.1.1
  socket_io_client: ^1.0.1
  firebase_storage:
  image_picker: ^0.8.4+4
  timeago: ^3.1.0
  date_utils: ^0.2.0
  image_cropper: ^1.4.1
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.0.2
  url_launcher: ^6.0.12
  http: ^0.13.4
  video_player: ^2.2.6
  grouped_list: ^4.1.0
  hive: ^2.0.6
  hive_flutter: ^1.0.0
  flutter_rating_bar: ^4.0.0
  easy_localization: ^3.0.0
  percent_indicator: ^3.0.1
  equatable: ^2.0.3
  progress_indicators: ^1.0.0
  pull_to_refresh: ^2.0.0
  jitsi_meet: ^4.0.0
  flutter:
    sdk: flutter
  cloud_firestore_odm: ^1.0.0-dev.10
  collection: ^1.14.13

dev_dependencies:
  build_runner: ^2.1.7
  cloud_firestore_odm_generator: ^1.0.0-dev.10
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/languages/
    - assets/svgs/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf


